'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    /*
      Add altering commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      */
      return queryInterface.bulkInsert('Games', [
        {title: 'Valheim',description: 'A brutal exploration and survival game for 1-10 players, set in a procedurally-generated purgatory inspired by viking culture. Battle, build, and conquer your way to a saga worthy of Odin’s patronage!',image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/892970/header.jpg?t=1612279371',publisherId: 1,consoleId: 1,genreId: 1,maxPlayers: 10,rating: 0,},
        {title: 'Mass Effect™ Legendary Edition',description: 'The Mass Effect™ Legendary Edition includes single-player base content and over 40 DLC from the highly acclaimed Mass Effect, Mass Effect 2, and Mass Effect 3 games, including promo weapons, armors, and packs — remastered and optimized for 4K Ultra HD.',image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1328670/header.jpg?t=1612289074',publisherId: 2,consoleId: 1,genreId: 2,maxPlayers: 1,rating: 0,},
        {title: 'Dyson Sphere Program',description: 'Build the most efficient intergalactic factory in space simulation strategy game Dyson Sphere Program! Harness the power of stars, collect resources, plan and design production lines and develop your interstellar factory from a small space workshop to a galaxy-wide industrial empire.',image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1366540/header.jpg?t=1612085806',publisherId: 3, consoleId: 1,genreId: 3,maxPlayers: 1,rating: 0,},
        {title: 'Rust',description: 'The only aim in Rust is to survive - Overcome struggles such as hunger, thirst and cold. Build a fire. Build a shelter. Kill animals. Protect yourself from other players.',image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/252490/header.jpg?t=1608404151',publisherId: 4,consoleId: 1,genreId: 4,maxPlayers: 500,rating: 0,},
        {title: 'Cyberpunk 2077',description: 'Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality.',image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg?t=1611573739',publisherId: 5,consoleId: 1,genreId: 5,maxPlayers: 1,rating: 0,},
        {title: 'Sea of Thieves',description: 'Sea of Thieves offers the essential pirate experience, from sailing and fighting to exploring and looting – everything you need to live the pirate life and become a legend in your own right. With no set roles, you have complete freedom to approach the world, and other players, however you choose.',image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1172620/header.jpg?t=1612047957',publisherId: 6,consoleId: 1,genreId: 1,maxPlayers: 4,rating: 0,},
        {title: 'Baldur’s Gate 3',description: 'Gather your party, and return to the Forgotten Realms in a tale of fellowship and betrayal, sacrifice and survival, and the lure of absolute power.',image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg?t=1610008080',publisherId: 7,consoleId: 1,genreId: 6,maxPlayers: 4,rating: 0,},
        {title: 'Sid Meier’s Civilization® VI',description: 'Civilization VI offers new ways to interact with your world, expand your empire across the map, advance your culture, and compete against history’s greatest leaders to build a civilization that will stand the test of time. Play as one of 20 historical leaders including Roosevelt (America) and Victoria (England).',image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/289070/header.jpg?t=1611862077',publisherId: 8,consoleId: 1,genreId: 7,maxPlayers: 12,rating: 0,},
        {title: 'Phasmophobia',description: 'Phasmophobia is a 4 player online co-op psychological horror. Paranormal activity is on the rise and it’s up to you and your team to use all the ghost hunting equipment at your disposal in order to gather as much evidence as you can.',image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/739630/header.jpg?t=1611245377',publisherId: 9,consoleId: 1,genreId: 8,maxPlayers: 4,rating: 0,},
        {title: 'Stardew Valley',description: 'You’ve inherited your grandfather’s old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to begin your new life. Can you learn to live off the land and turn these overgrown fields into a thriving home?',image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/413150/header.jpg?t=1608624324',publisherId: 10,consoleId: 1,genreId: 3,maxPlayers: 4,rating: 0,},
        {title: 'Raft',description: 'Raft throws you and your friends into an epic oceanic adventure! Alone or together, players battle to survive a perilous voyage across a vast sea! Gather debris, scavenge reefs and build your own floating home, but be wary of the man-eating sharks!',image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/648800/header.jpg?t=1602795811',publisherId: 11,consoleId: 1,genreId: 4,maxPlayers: 2,rating: 0,},
        {title: 'Plague Inc: Evolved',description: 'Plague Inc: Evolved is a unique mix of high strategy and terrifyingly realistic simulation. Your pathogen has just infected ’Patient Zero’ - now you must bring about the end of human history by evolving a deadly, global Plague whilst adapting against everything humanity can do to defend itself.',image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/246620/header.jpg?t=1611835557',publisherId: 12,consoleId: 1,genreId: 7,maxPlayers: 2,rating: 0,},
        {title: 'OMORI',description: 'Explore a strange world full of colorful friends and foes. When the time comes, the path you’ve chosen will determine your fate... and perhaps the fate of others as well.',image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1150690/header.jpg?t=1609260441',publisherId: 13,consoleId: 1,genreId: 8,maxPlayers: 1,rating: 0,},
        {title: 'ARK: Survival Evolved',description: 'Stranded on the shores of a mysterious island, you must learn to survive. Use your cunning to kill or tame the primeval creatures roaming the land, and encounter other players to survive, dominate... and escape!',image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/346110/header.jpg?t=1608086122',publisherId: 14,consoleId: 1,genreId: 4,maxPlayers: 70,rating: 0,},
        {title: 'DayZ',description: 'How long can you survive a post-apocalyptic world? A land overrun with an infected "zombie" population, where you compete with other survivors for limited resources. Will you team up with strangers and stay strong together? Or play as a lone wolf to avoid betrayal? This is DayZ – this is your story.',image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/221100/header.jpg?t=1608209844',publisherId: 15,consoleId: 1,genreId: 4,maxPlayers: 60,rating: 0,},
        {title: 'Beat Saber',description: 'Beat Saber is a VR rhythm game where you slash the beats of adrenaline-pumping music as they fly towards you, surrounded by a futuristic world.',image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/620980/header.jpg?t=1605633883',publisherId: 16,consoleId: 1,genreId: 9,maxPlayers: 2,rating: 0,},
        {title: 'GTA V',description: 'Grand Theft Auto V for PC offers players the option to explore the award-winning world of Los Santos and Blaine County in resolutions of up to 4k and beyond, as well as the chance to experience the game running at 60 frames per second.',image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/271590/header.jpg?t=1592866696',publisherId: 17,consoleId: 2,genreId: 10,maxPlayers: 16,rating: 0,},
        {title: 'Modern Warfare® 3',description: 'The best-selling first-person action series of all-time returns with an epic sequel to the multiple GOTY award winner Call of Duty®: Modern Warfare® 2',image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/115300/header.jpg?t=1569365100',publisherId: 18,consoleId: 2,genreId: 11,maxPlayers: 18,rating: 0,},
        {title: 'Halo: Reach',description: 'The Master Chief’s iconic journey includes six games, built for PC and collected in a single integrated experience. Whether you’re a long-time fan or meeting Spartan 117 for the first time, The Master Chief Collection is the definitive Halo gaming experience.',image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1064220/header.jpg?t=1591395907',publisherId: 19,consoleId: 2,genreId: 11,maxPlayers: 16,rating: 0,},
        {title: 'Destiny 2',description: 'Destiny 2 is an action MMO with a single evolving world that you and your friends can join anytime, anywhere, absolutely free.',image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1085660/header.jpg?t=1607380522',publisherId: 20,consoleId: 2,genreId: 11,maxPlayers: 16,rating: 0,},
        {title: 'Borderlands 3',description: 'The original shooter-looter returns, packing bazillions of guns and a mayhem-fueled adventure! Blast through new worlds & enemies and save your home from the most ruthless cult leaders in the galaxy.',image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/397540/header.jpg?t=1611688304',publisherId: 8,consoleId: 1,genreId: 2,maxPlayers: 2,rating: 0,},
        
    ], {});
  },

  down: (queryInterface, Sequelize) => {
    /*
      Add reverting commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      */
      return queryInterface.bulkDelete('Games', null, {});
  }
};
